name: Documentation

on:
  push:
    branches:
      - abstract
  pull_request:
    branches:
      - abstract 

jobs:
  build_docs:
    runs-on: ubuntu-latest
    permissions:                
      contents: write           
      pull-requests: write 
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11' 

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
        working-directory: docs
      - name: Install Dependencies
        run: |
          pip install .
      - name: Generate source
        run: |
          sphinx-apidoc -o source ../mind_the_gaps/
        working-directory: docs

      - name: Build Documentation
        run: |
          make html  
        working-directory: docs

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        id: auto-commit-action
        with:
          commit_message: Push workflow built docs
        #github_token: ${{ secrets.GITHUB_TOKEN }}
        #branch: ${{ github.ref }}

      - name: "Run if changes have been detected"
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        run: echo "Changes!"
      
      - name: "Run if no changes have been detected"
        if: steps.auto-commit-action.outputs.changes_detected == 'false'
        run: echo "No Changes!"


#      - name: Deploy to Read the Docs
#        uses: rtfd/readthedocs-github-action@v1
#        with:
#          version: latest
#          output_dir: _build/html  # Path to the built documentation
#        env:
#          READTHEDOCS_API_TOKEN: ${{ secrets.READTHEDOCS_API_TOKEN }}
